{% set name = "scooby" %}
{% set version = "0.5.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 874828e38834c1ccb2236a7491e0739675086608c6588abf132cdd0049458192

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - scooby

about:
  home: https://github.com/banesullivan/scooby/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight toolset to easily report your Python environment's package versions and hardware resources.
  description: |
    Scooby has HTML formatting for Jupyter notebooks and rich text formatting for just about every other environment. We designed this module to be lightweight such that it could easily be added as a dependency to Python projects for environment reporting when debugging. Simply add scooby to your dependencies and implement a function to have scooby report on the aspects of the environment you care most about.
  doc_url: https://github.com/banesullivan/scooby/blob/master/README.md
  dev_url: https://github.com/banesullivan/scooby

extra:
  recipe-maintainers:
    - banesullivan
    - prisae
