{% set name = "scooby" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dedeef3d4c5f08e885e2157e5b063a6493f58a961c8e179947e2f8cc9834ae40

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - scooby

about:
  home: https://github.com/banesullivan/scooby/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A lightweight toolset to easily report your Python environment's package versions and hardware resources."
  description: |
    Scooby has HTML formatting for Jupyter notebooks and rich text formatting for just about every other environment. We designed this module to be lightweight such that it could easily be added as a dependency to Python projects for environment reporting when debugging. Simply add scooby to your dependencies and implement a function to have scooby report on the aspects of the environment you care most about.
  doc_url: https://github.com/banesullivan/scooby/blob/master/README.md
  dev_url: https://github.com/banesullivan/scooby

extra:
  recipe-maintainers:
    - banesullivan
    - prisae
