travis:
  secure:
    BINSTAR_TOKEN: NNB+OODBQwIJxY2QLpGkX0AaZrYGKH4eAT1HNEQaNLVpFiytHBen485VMUt+huLWE2u+y3cROLtXT988ehvD97TPKZw8tXZbcixsRPFBAhMLCoOVEYzlRGW1GpR7mxA2nMMvJQef8T5L5lG2b8G1FFoYacmV2wYI/WkBF78kOazasD7i3BDkH18mwrisQNomFDXExaKa+dHbyfoNvL6+aEi8hpIAj5SW1/iGE6VmJMX51izyhED8ye7MyyDhMjBYix6Ljk3BciQ4h3jw6PhW07r5gwgPIJ4y1an6hTsuaSaExECGCpimBnZxqUZb8P5mDmuFNJVhpZA7X8t1qcLjZeLO3aH0VQIGxkEehq6jnAHeA9lb7Np9OtS/BPEl3gUEHYSOHvvVeXSsHgS9I8gm8E5zfw/Ezr9+A3VAd331ON9qIe5nZ8Ty7s1Shg7OPyd+1RWrxkW0d4KbhTDERGkK4pDoMuX/ALFKsmAQ68rvhlB2SfYO1HbqYwi70Xpt0639+soaYA7qR/Cx/j6EsYSYkuzJAdmtYfk8NYDfPqZYkP+DM8QmRE+uZjSoFTQRTRu1QALc3EOo4hUaficVRxrNpKPQNbU4W5ALitA5nGsUgFiPJ40+Pbogh+8XJhW1rEj7Q9Fd+MOByPzyh3BEeoB4bPTrZTu3vn8n3WGqxX2gGZ0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
